# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=512)),
                ('address_line_two', models.CharField(blank=True, max_length=512)),
                ('suburb', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('TAS', 'Tasmania'), ('WA', 'Western Australia'), ('NT', 'Norther Territory'), ('ACT', 'Australian Capital Territory')], max_length=5)),
                ('postcode', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AltCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AltPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=512)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='meat.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('postcode', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('logo', models.FileField(blank=True, max_length=512, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='cut',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='meat.Part'),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='meat.Supplier'),
        ),
        migrations.AddField(
            model_name='altpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt', to='meat.Part'),
        ),
        migrations.AddField(
            model_name='altcut',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt', to='meat.Cut'),
        ),
        migrations.AddField(
            model_name='address',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='meat.Supplier'),
        ),
    ]
